// ─────────────────────────────────────────────────────────────────────────────
// Sector tracker DATA — all 8 sectors with 4 quarters (Q1-Q4 2026) each.
// ─────────────────────────────────────────────────────────────────────────────
import type { TrackerSector } from './trackerData';

export const TRACKERS: TrackerSector[] = [
  {
    slug: 'quick-commerce', name: 'Quick Commerce', shortName: 'Quick Comm.', icon: '⚡',
    tagline: '10-minute grocery & essentials', coverGradient: ['#0ea5e9', '#1d4ed8'],
    thesis: 'Quick commerce has moved from "race to scale" to "race to unit economics." Blinkit, Zepto and Swiggy Instamart dominate a fast-consolidating market, and the next 12 months will decide who converts GMV leadership into durable contribution margin — and who gets absorbed or exits.',
    quarters: {
      'Q1-2026': { temperature: 72, consensus: 'CONSENSUS BULL', headline: 'Dark store networks expanding rapidly with ₹1T+ annual GMV potential and a hard pivot to profitability.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '1,12,000', suffix: '₹ Cr', change: '+55% YoY', changeType: 'up', sparkline: [48, 61, 74, 88, 96, 112] },
          { label: 'Dark Stores (Top 3)', value: '4,200', suffix: 'stores', change: '+180% YoY', changeType: 'up', sparkline: [1500, 2100, 2800, 3400, 3900, 4200] },
          { label: 'Top-3 Market Share', value: '95', suffix: '%', change: 'stable', changeType: 'flat', sparkline: [88, 90, 92, 94, 95, 95] },
          { label: 'Avg. Delivery Time', value: '11', suffix: 'min', change: '-2 min YoY', changeType: 'up', sparkline: [16, 15, 14, 13, 12, 11] },
        ] },
      'Q2-2026': { temperature: 74, consensus: 'CONSENSUS BULL', headline: 'Contribution margins turning positive as order density and private-label mix drive economics.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '1,28,000', suffix: '₹ Cr', change: '+58% YoY', changeType: 'up', sparkline: [52, 66, 80, 96, 112, 128] },
          { label: 'Dark Stores (Top 3)', value: '5,000', suffix: 'stores', change: '+190% YoY', changeType: 'up', sparkline: [1700, 2400, 3200, 4000, 4600, 5000] },
          { label: 'Top-3 Market Share', value: '96', suffix: '%', change: 'consolidating', changeType: 'up', sparkline: [89, 91, 93, 95, 95, 96] },
          { label: 'Avg. Delivery Time', value: '10.5', suffix: 'min', change: '-0.5 min QoQ', changeType: 'up', sparkline: [16, 15, 14, 12.5, 11, 10.5] },
        ] },
      'Q3-2026': { temperature: 75, consensus: 'CONSENSUS BULL', headline: 'Private labels and ad revenue push gross margins toward 30% as the sector scales.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '1,45,000', suffix: '₹ Cr', change: '+60% YoY', changeType: 'up', sparkline: [56, 72, 90, 108, 128, 145] },
          { label: 'Dark Stores (Top 3)', value: '5,800', suffix: 'stores', change: '+200% YoY', changeType: 'up', sparkline: [1800, 2600, 3600, 4500, 5200, 5800] },
          { label: 'Gross Margin', value: '28', suffix: '%', change: '+4pp QoQ', changeType: 'up', sparkline: [18, 20, 23, 25, 26, 28] },
          { label: 'Avg. Delivery Time', value: '10', suffix: 'min', change: 'flat', changeType: 'flat', sparkline: [16, 15, 13.5, 12, 11, 10] },
        ] },
      'Q4-2026': { temperature: 73, consensus: 'CONSENSUS BULL', headline: 'Festive surge and margin expansion drive a landmark year for quick-commerce economics.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '1,62,000', suffix: '₹ Cr', change: '+62% YoY', changeType: 'up', sparkline: [60, 78, 98, 118, 140, 162] },
          { label: 'Dark Stores (Top 3)', value: '6,500', suffix: 'stores', change: '+210% YoY', changeType: 'up', sparkline: [1900, 2800, 4000, 5000, 5800, 6500] },
          { label: 'Gross Margin', value: '31', suffix: '%', change: '+3pp QoQ', changeType: 'up', sparkline: [19, 22, 25, 27, 29, 31] },
          { label: 'Avg. Delivery Time', value: '9.5', suffix: 'min', change: '-0.5 min QoQ', changeType: 'up', sparkline: [15.5, 14, 13, 11.5, 10.5, 9.5] },
        ] },
    },
    subSectors: [
      { name: 'Grocery', share: 58, growth: '+60% YoY', cagr: '38%', players: ['Blinkit', 'Zepto', 'Instamart'] },
      { name: 'Snacks & Beverages', share: 20, growth: '+48% YoY', cagr: '30%', players: ['Zepto', 'Blinkit', 'BigBasket'] },
      { name: 'Beauty & Personal Care', share: 12, growth: '+70% YoY', cagr: '42%', players: ['Blinkit', 'Zepto'] },
      { name: 'Over-the-counter Health', share: 10, growth: '+55% YoY', cagr: '35%', players: ['Blinkit', 'Instamart'] },
    ],
    competitive: [
      { player: 'Blinkit', rank: 1, metric: 'Market Share', value: '~46%', trend: 'up', note: 'Largest network, expanding to 1,000+ stores' },
      { player: 'Zepto', rank: 2, metric: 'Market Share', value: '~30%', trend: 'up', note: 'Fastest growth, strong in metros' },
      { player: 'Swiggy Instamart', rank: 3, metric: 'Market Share', value: '~19%', trend: 'flat', note: 'Aggregator-led, improving economics' },
      { player: 'BigBasket (BB Now)', rank: 4, metric: 'Market Share', value: '~5%', trend: 'down', note: 'Turning around under Tata' },
    ],
    trends: [
      { title: 'Move to Positive Contribution', impact: 'High', direction: 'up', description: 'Blinkit and Zepto guiding to positive contribution margin as average order value climbs above ₹450.' },
      { title: 'Dark Store Consolidation', impact: 'High', direction: 'up', description: 'Capital is concentrating; smaller players are exiting or being acquired.' },
      { title: 'Premium & Non-Grocery SKUs', impact: 'Medium', direction: 'up', description: 'Beauty, personal care and OTC now ~22% of GMV with higher margins.' },
      { title: 'Weather & Promo Normalisation', impact: 'Low', direction: 'flat', description: 'Order density normalising post-festive as players rationalise discounts.' },
    ],
    regulatory: [
      { title: 'E-commerce Policy 2.0', date: 'Q3 2026', status: 'Pending', description: 'Proposed rules on dark stores and marketplace-vs-inventory classification.' },
      { title: 'FSSAI Compliance for Dark Stores', date: 'Ongoing', status: 'Implemented', description: 'Licensing norms for micro-fulfilment and last-mile food storage.' },
      { title: 'Consumer Protection (E-com) Rules', date: 'Under review', status: 'Planned', description: 'Return, refund and delivery-timing disclosure mandates.' },
    ],
    swot: {
      strengths: ['Fastest delivery network in India', 'High repeat purchase / app stickiness', 'Strong private-label upside'],
      weaknesses: ['Unit economics still thin', 'High capital intensity per store', 'Dependence on gig workforce'],
      opportunities: ['Private labels & premium categories', 'Own-brand margin expansion', 'Tier-1/2 expansion'],
      threats: ['Aggregator counterattack (Swiggy/Zomato)', 'Regulatory scrutiny', 'Burn-rate funded price wars'],
    },
    outlook: {
      marketSize2027: '₹1.2T', cagr: '38%',
      projection: [{ year: '2024', value: 45 }, { year: '2025', value: 74 }, { year: '2026', value: 112 }, { year: '2027', value: 160 }],
      drivers: ['Unit economics turnaround', 'Private-label penetration', 'Dark store density'],
      risks: ['Regulatory caps on delivery', 'Funding winter returns', 'Aggregator margin war'],
    },
    catalysts: [
      { title: 'Blinkit EBITDA-positive quarter', timing: 'Q1 FY27', type: 'Catalyst' },
      { title: 'Zepto IPO filing', timing: 'H2 2026', type: 'Watch' },
      { title: 'Dark store licensing review', timing: 'Q3 2026', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Blinkit Contribution Margin', value: '+2.8%', note: 'of GOV, Q1 FY27 guide', trend: 'up' },
      { label: 'Zepto EBITDA Trajectory', value: 'Near breakeven', note: 'before levies', trend: 'up' },
      { label: 'Average Order Value', value: '₹486', note: 'platform blended', trend: 'up' },
      { label: 'Delivery Cost per Order', value: '₹38', note: 'incl. dark-store labor', trend: 'down' },
      { label: 'Blinkit Dark-Store Payback', value: '18 months', note: 'metro clusters', trend: 'up' },
      { label: 'Private-Label Share of GMV', value: '9%', note: 'up 3pp in two quarters', trend: 'up' },
    ],
  },
  {
    slug: 'fintech', name: 'Fintech', shortName: 'Fintech', icon: '💳',
    tagline: 'Payments, lending, wealth & insurance', coverGradient: ['#0d6e6e', '#064e3b'],
    thesis: 'India fintech is maturing from user-acquisition to profitability and compliance. UPI-led rails, neobank scale and AI underwriting are expanding the market, while tightening RBI norms and a "funding winter for unprofitable scale" separate winners from casualties.',
    quarters: {
      'Q1-2026': { temperature: 68, consensus: 'CONSENSUS BULL', headline: 'Digital payments penetration reaches 80% with UPI dominance — a $1.3T market by 2027.',
        keyMetrics: [
          { label: 'UPI Monthly Transactions', value: '18.4', suffix: 'B', change: '+48% YoY', changeType: 'up', sparkline: [9.5, 11.2, 13.0, 15.1, 17.0, 18.4] },
          { label: 'Digital Payments Penetration', value: '80', suffix: '%', change: '+15pp YoY', changeType: 'up', sparkline: [52, 58, 64, 70, 75, 80] },
          { label: 'Fintech Funding (FY25)', value: '2.1', suffix: '$B', change: '-12% YoY', changeType: 'down', sparkline: [3.9, 3.1, 2.9, 2.4, 2.3, 2.1] },
          { label: 'Neobank Users', value: '45', suffix: 'M', change: '+85% YoY', changeType: 'up', sparkline: [12, 18, 26, 34, 40, 45] },
        ] },
      'Q2-2026': { temperature: 70, consensus: 'CONSENSUS BULL', headline: 'Credit on UPI scales nationally as funding stabilises and profitability leadership firms up.',
        keyMetrics: [
          { label: 'UPI Monthly Transactions', value: '20.1', suffix: 'B', change: '+51% YoY', changeType: 'up', sparkline: [10.2, 12.3, 14.4, 16.7, 18.4, 20.1] },
          { label: 'Digital Payments Penetration', value: '83', suffix: '%', change: '+3pp QoQ', changeType: 'up', sparkline: [55, 61, 67, 73, 78, 83] },
          { label: 'Fintech Funding (YTD)', value: '1.4', suffix: '$B', change: 'recovering', changeType: 'up', sparkline: [3.9, 3.1, 2.9, 2.4, 2.3, 1.4] },
          { label: 'Neobank Users', value: '54', suffix: 'M', change: '+90% YoY', changeType: 'up', sparkline: [14, 21, 30, 39, 46, 54] },
        ] },
      'Q3-2026': { temperature: 71, consensus: 'CONSENSUS BULL', headline: 'RBI digital-lending norms and DPDPA compliance reshape the competitive landscape.',
        keyMetrics: [
          { label: 'UPI Monthly Transactions', value: '22.0', suffix: 'B', change: '+53% YoY', changeType: 'up', sparkline: [11, 13.5, 16, 18.5, 20.1, 22] },
          { label: 'Digital Payments Penetration', value: '85', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [57, 63, 70, 76, 80, 85] },
          { label: 'Credit-on-UPI Monthly Value', value: '3.2', suffix: '$B', change: 'new metric', changeType: 'up', sparkline: [0.4, 0.9, 1.5, 2.1, 2.7, 3.2] },
          { label: 'Neobank Users', value: '62', suffix: 'M', change: '+92% YoY', changeType: 'up', sparkline: [16, 24, 34, 44, 52, 62] },
        ] },
      'Q4-2026': { temperature: 69, consensus: 'CONSENSUS BULL', headline: 'Consolidation accelerates; profitable scale and compliance become the moat.',
        keyMetrics: [
          { label: 'UPI Monthly Transactions', value: '24.0', suffix: 'B', change: '+55% YoY', changeType: 'up', sparkline: [12, 15, 17.5, 20.5, 22, 24] },
          { label: 'Digital Payments Penetration', value: '86', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [58, 65, 72, 78, 82, 86] },
          { label: 'Credit-on-UPI Monthly Value', value: '4.1', suffix: '$B', change: '+28% QoQ', changeType: 'up', sparkline: [0.5, 1.1, 1.9, 2.6, 3.2, 4.1] },
          { label: 'Neobank Users', value: '70', suffix: 'M', change: '+95% YoY', changeType: 'up', sparkline: [18, 27, 38, 50, 60, 70] },
        ] },
    },
    subSectors: [
      { name: 'Payments', share: 45, growth: '+35% YoY', cagr: '24%', players: ['PhonePe', 'Google Pay', 'Paytm', 'Razorpay'] },
      { name: 'Lending', share: 28, growth: '+22% YoY', cagr: '18%', players: ['Lendingkart', 'Capital Float', 'KreditBee', 'ZestMoney'] },
      { name: 'Insurtech', share: 12, growth: '+62% YoY', cagr: '32%', players: ['Policybazaar', 'Acko', 'Digit', 'Coverfox'] },
      { name: 'Wealthtech', share: 8, growth: '+110% YoY', cagr: '45%', players: ['Zerodha', 'Groww', 'Upstox', 'Smallcase'] },
      { name: 'Neobanking', share: 7, growth: '+85% YoY', cagr: '40%', players: ['Jupiter', 'Fi', 'Niyo', 'Open'] },
    ],
    competitive: [
      { player: 'PhonePe', rank: 1, metric: 'UPI Share', value: '~48%', trend: 'up', note: 'Dominant in UPI value and volume' },
      { player: 'Google Pay', rank: 2, metric: 'UPI Share', value: '~35%', trend: 'flat', note: 'Stable, expanding to credit' },
      { player: 'Paytm', rank: 3, metric: 'UPI Share', value: '~7%', trend: 'down', note: 'Reorganising into enterprise fintech' },
      { player: 'Razorpay', rank: 4, metric: 'Business Payments', value: '~20%', trend: 'up', note: 'Leading online merchant acquiring' },
    ],
    trends: [
      { title: 'Credit on UPI (UPI 2.0)', impact: 'High', direction: 'up', description: 'Pre-approved credit lines on UPI opening new lending rails and fee pools.' },
      { title: 'RBI Regulatory Tightening', impact: 'High', direction: 'down', description: 'Digital lending and disclosure norms raise compliance costs and curtail risky BNPL.' },
      { title: 'M&A Consolidation', impact: 'High', direction: 'up', description: 'Funding tightening is driving mergers and acqui-hires across lending and wealth.' },
      { title: 'AI Underwriting & Fraud', impact: 'Medium', direction: 'up', description: 'ML credit scoring and fraud detection becoming the core differentiator.' },
    ],
    regulatory: [
      { title: 'RBI Digital Lending Guidelines', date: 'Dec 2025', status: 'Implemented', description: 'Cap on DLAs, full disclosure and grievance redressal mandates.' },
      { title: 'DPDPA Compliance Deadline', date: 'Mar 2026', status: 'Pending', description: 'Data fiduciary obligations and consent architecture go live.' },
      { title: 'CBDC Pilot Expansion', date: 'Q2 2026', status: 'Planned', description: 'Broader e₹-R rollout with offline capability.' },
    ],
    swot: {
      strengths: ['World-class UPI rails', 'Large underbanked base', 'Deep payment data moat'],
      weaknesses: ['Regulatory compliance burden', 'Thin margins on payments', 'Funding winter for late-stage'],
      opportunities: ['Credit on UPI', 'AI underwriting', 'Wealthtech & SIP penetration'],
      threats: ['RBI scrutiny', 'Data-privacy enforcement', 'BigTech entry'],
    },
    outlook: {
      marketSize2027: '$1.3T', cagr: '22%',
      projection: [{ year: '2024', value: 620 }, { year: '2025', value: 780 }, { year: '2026', value: 950 }, { year: '2027', value: 1300 }],
      drivers: ['UPI innovation', 'Financial inclusion', 'API banking', 'AI underwriting'],
      risks: ['Regulatory changes', 'Cybersecurity threats', 'Funding winter', 'Profitability pressure'],
    },
    catalysts: [
      { title: 'Credit-on-UPI scaling nationally', timing: 'FY27', type: 'Catalyst' },
      { title: 'DPDPA deadline impact', timing: 'Mar 2026', type: 'Watch' },
      { title: 'RBI BNPL review', timing: 'Q2 2026', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Per-Transaction Revenue (UPI)', value: '₹0.12', note: 'industry blended', trend: 'down' },
      { label: 'BNPL Default Rates', value: '3.4%', note: '90dpd, Q2 2026', trend: 'flat' },
      { label: 'Neobank CAC vs LTV', value: '1:3.2', note: '18-month payback', trend: 'up' },
      { label: 'Payment Gateway Share', value: 'Razorpay 32%', note: 'online merchant acquiring', trend: 'up' },
      { label: 'Lending Fintech NIM', value: '9.8%', note: 'blended portfolio', trend: 'up' },
      { label: 'Regulatory Compliance Cost', value: '2.1%', note: 'of revenue, top-5 lenders', trend: 'up' },
    ],
  },
  {
    slug: 'ev', name: 'Electric Vehicles', shortName: 'EV', icon: '🔋',
    tagline: 'Two-wheelers, four-wheelers & charging', coverGradient: ['#059669', '#065f46'],
    thesis: 'The Indian EV story is being led by two-wheelers, where cost parity and FAME support have driven a step-change in adoption. Four-wheeler and charging infrastructure remain the long-lead items; battery chemistry and localisation now decide the winners.',
    quarters: {
      'Q1-2026': { temperature: 66, consensus: 'CONSENSUS BULL', headline: 'Two-wheeler EV sales surge 300% YoY with strong policy tailwinds and battery-cost deflation.',
        keyMetrics: [
          { label: '2W EV Sales', value: '1.2', suffix: 'M units', change: '+300% YoY', changeType: 'up', sparkline: [0.3, 0.45, 0.6, 0.85, 1.05, 1.2] },
          { label: '2W EV Market Share', value: '8.3', suffix: '%', change: '+5pp YoY', changeType: 'up', sparkline: [2.1, 3.2, 4.5, 6.1, 7.2, 8.3] },
          { label: 'Public Charging Points', value: '25,000', suffix: '+', change: '+120% YoY', changeType: 'up', sparkline: [4000, 8000, 13000, 18000, 22000, 25000] },
          { label: 'Battery Cell Cost', value: '112', suffix: '$/kWh', change: '-18% YoY', changeType: 'up', sparkline: [160, 148, 138, 128, 120, 112] },
        ] },
      'Q2-2026': { temperature: 64, consensus: 'CONSENSUS BULL', headline: 'Adoption deepens but subsidy uncertainty and charging gaps temper the 4W story.',
        keyMetrics: [
          { label: '2W EV Sales', value: '1.35', suffix: 'M units', change: '+310% YoY', changeType: 'up', sparkline: [0.32, 0.5, 0.68, 0.92, 1.15, 1.35] },
          { label: '2W EV Market Share', value: '9.1', suffix: '%', change: '+0.8pp QoQ', changeType: 'up', sparkline: [2.3, 3.5, 5.0, 6.8, 8.0, 9.1] },
          { label: 'Public Charging Points', value: '30,000', suffix: '+', change: '+125% YoY', changeType: 'up', sparkline: [4500, 9500, 15500, 21500, 26000, 30000] },
          { label: 'Battery Cell Cost', value: '105', suffix: '$/kWh', change: '-20% YoY', changeType: 'up', sparkline: [158, 144, 132, 121, 112, 105] },
        ] },
      'Q3-2026': { temperature: 62, consensus: 'MIXED SIGNALS', headline: 'Policy taper creates near-term noise while 3W and commercial segments accelerate.',
        keyMetrics: [
          { label: '2W EV Sales', value: '1.5', suffix: 'M units', change: '+315% YoY', changeType: 'up', sparkline: [0.35, 0.55, 0.75, 1.0, 1.25, 1.5] },
          { label: '2W EV Market Share', value: '9.8', suffix: '%', change: '+0.7pp QoQ', changeType: 'up', sparkline: [2.5, 3.8, 5.5, 7.4, 8.6, 9.8] },
          { label: '3W EV Sales', value: '0.28', suffix: 'M units', change: '+95% YoY', changeType: 'up', sparkline: [0.06, 0.1, 0.15, 0.2, 0.24, 0.28] },
          { label: 'Battery Cell Cost', value: '98', suffix: '$/kWh', change: '-22% YoY', changeType: 'up', sparkline: [155, 140, 127, 115, 105, 98] },
        ] },
      'Q4-2026': { temperature: 63, consensus: 'CONSENSUS BULL', headline: 'Localisation and falling battery costs restore the structural bull case into FY27.',
        keyMetrics: [
          { label: '2W EV Sales', value: '1.68', suffix: 'M units', change: '+320% YoY', changeType: 'up', sparkline: [0.38, 0.6, 0.82, 1.1, 1.38, 1.68] },
          { label: '2W EV Market Share', value: '10.5', suffix: '%', change: '+0.7pp QoQ', changeType: 'up', sparkline: [2.7, 4.1, 6.0, 8.0, 9.3, 10.5] },
          { label: 'Public Charging Points', value: '38,000', suffix: '+', change: '+130% YoY', changeType: 'up', sparkline: [5000, 11000, 19000, 27000, 33000, 38000] },
          { label: 'Battery Cell Cost', value: '92', suffix: '$/kWh', change: '-24% YoY', changeType: 'up', sparkline: [150, 135, 121, 110, 100, 92] },
        ] },
    },
    subSectors: [
      { name: '2W EV', share: 62, growth: '+300% YoY', cagr: '48%', players: ['Ola Electric', 'TVS', 'Ather', 'Bajaj'] },
      { name: '3W EV', share: 18, growth: '+90% YoY', cagr: '35%', players: ['Mahindra', 'Piaggio', 'Bajaj'] },
      { name: 'Passenger EV', share: 12, growth: '+65% YoY', cagr: '42%', players: ['Tata', 'MG', 'Mahindra', 'BYD'] },
      { name: 'Commercial EV', share: 8, growth: '+40% YoY', cagr: '28%', players: ['Tata Ace EV', 'Mahindra', 'Euler'] },
    ],
    competitive: [
      { player: 'Ola Electric', rank: 1, metric: '2W EV Share', value: '~30%', trend: 'down', note: 'Market leader but losing share to TVS/Bajaj' },
      { player: 'TVS Motor', rank: 2, metric: '2W EV Share', value: '~22%', trend: 'up', note: 'Rapid ramp via iQube and supply chain' },
      { player: 'Bajaj Auto', rank: 3, metric: '2W EV Share', value: '~18%', trend: 'up', note: 'Chetak expanding across cities' },
      { player: 'Ather Energy', rank: 4, metric: '2W EV Share', value: '~12%', trend: 'flat', note: 'Premium positioning, network expansion' },
    ],
    trends: [
      { title: 'Battery Cost Deflation', impact: 'High', direction: 'up', description: 'Falling cell prices are driving 2W EV toward upfront cost parity with ICE.' },
      { title: 'FAME III / PM E-DRIVE', impact: 'High', direction: 'up', description: 'Demand incentive re-targeted toward high-utilisation segments.' },
      { title: 'Localisation & PLI', impact: 'Medium', direction: 'up', description: 'Battery-cell and component localisation lowering landed costs.' },
      { title: 'Charging Network Build-out', impact: 'Medium', direction: 'up', description: 'Fast-charging density growing but still a friction point for 4W.' },
    ],
    regulatory: [
      { title: 'FAME III / PM E-DRIVE rollout', date: 'FY26', status: 'Implemented', description: 'Incentives for 2W, 3W and buses with localisation requirements.' },
      { title: 'Battery Swapping Standards', date: 'Q3 2026', status: 'Pending', description: 'Interoperability norms for swappable battery packs.' },
      { title: 'Battery Recycling Rules', date: 'Q2 2026', status: 'Planned', description: 'Extended producer responsibility for lithium-ion batteries.' },
    ],
    swot: {
      strengths: ['2W EV cost parity achieved', 'PLI & subsidy support', 'Falling battery costs'],
      weaknesses: ['Charging infrastructure gaps', 'Range anxiety (4W)', 'Export exposure risk'],
      opportunities: ['Battery localisation', 'Fleet & commercial adoption', 'Export markets'],
      threats: ['Policy flip-flops', 'Commodity price spikes', 'Chinese supply-chain dependence'],
    },
    outlook: {
      marketSize2027: '₹2.4T', cagr: '45%',
      projection: [{ year: '2024', value: 0.8 }, { year: '2025', value: 1.3 }, { year: '2026', value: 1.8 }, { year: '2027', value: 2.4 }],
      drivers: ['Cost parity', 'Infrastructure build', 'Fleet electrification'],
      risks: ['Subsidy tapering', 'Cell supply constraints', 'Competition intensity'],
    },
    catalysts: [
      { title: '2W EV crossing 10% penetration', timing: 'FY27', type: 'Catalyst' },
      { title: 'Battery swapping standards', timing: 'Q3 2026', type: 'Watch' },
      { title: 'FAME budget revision', timing: 'FY27 Budget', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Battery Cost per kWh (pack)', value: '$95', note: 'blended LFP, Q2 2026', trend: 'down' },
      { label: 'Ola vs Ather Share Gap', value: '18pp', note: 'narrowing', trend: 'down' },
      { label: 'FAME III Subsidy Impact', value: '₹11k', note: 'per 2W unit', trend: 'flat' },
      { label: '2W EV Contribution Margin', value: '+6.2%', note: 'top-3 OEMs', trend: 'up' },
      { label: 'Charge-Point Utilization', value: '14%', note: 'public DC fast chargers', trend: 'up' },
      { label: 'Localisation Rate (2W EV)', value: '78%', note: 'of BOM, top-2 OEMs', trend: 'up' },
    ],
  },
  {
    slug: 'food-delivery', name: 'Food Delivery', shortName: 'Food', icon: '🍕',
    tagline: 'Aggregators, cloud kitchens & quick service', coverGradient: ['#ea580c', '#9a3412'],
    thesis: 'Food delivery is exiting the discount wars. Zomato and Swiggy now compete on execution, premium segments and capital efficiency. The next catalyst is margin delivery: contribution margin turned positive for both, and profitability is now the headline metric investors demand.',
    quarters: {
      'Q1-2026': { temperature: 58, consensus: 'NEUTRAL-POSITIVE', headline: 'Platform economics stabilizing with sharp focus on contribution margin and a land-grab in quick commerce.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '35,000', suffix: '₹ Cr', change: '+22% YoY', changeType: 'up', sparkline: [20, 24, 27, 30, 33, 35] },
          { label: 'Zomato Contribution Margin', value: '4.8', suffix: '%', change: 'positive', changeType: 'up', sparkline: [-2.1, -0.8, 0.6, 2.2, 3.6, 4.8] },
          { label: 'Order Frequency', value: '3.2', suffix: '/mo', change: '+0.4 YoY', changeType: 'up', sparkline: [2.2, 2.4, 2.6, 2.9, 3.1, 3.2] },
          { label: 'Platform Market Share', value: '55/42', suffix: 'Swiggy/Zomato', change: 'stable', changeType: 'flat', sparkline: [52, 54, 55, 56, 55, 55] },
        ] },
      'Q2-2026': { temperature: 60, consensus: 'CONSENSUS BULL', headline: 'Margin delivery accelerates as ad revenue and subscriptions lift take rates for both majors.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '38,000', suffix: '₹ Cr', change: '+24% YoY', changeType: 'up', sparkline: [21, 26, 29, 33, 36, 38] },
          { label: 'Zomato Contribution Margin', value: '5.4', suffix: '%', change: '+0.6pp QoQ', changeType: 'up', sparkline: [-1.8, -0.4, 1.0, 2.8, 4.3, 5.4] },
          { label: 'Order Frequency', value: '3.4', suffix: '/mo', change: '+0.2 QoQ', changeType: 'up', sparkline: [2.3, 2.5, 2.8, 3.1, 3.3, 3.4] },
          { label: 'Ads Share of Revenue', value: '31', suffix: '%', change: '+5pp YoY', changeType: 'up', sparkline: [15, 18, 22, 25, 28, 31] },
        ] },
      'Q3-2026': { temperature: 61, consensus: 'CONSENSUS BULL', headline: 'Aggregators extend into instant commerce and premium dining to expand the TAM.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '41,500', suffix: '₹ Cr', change: '+25% YoY', changeType: 'up', sparkline: [22, 28, 32, 36, 39, 41.5] },
          { label: 'Zomato Contribution Margin', value: '6.0', suffix: '%', change: '+0.6pp QoQ', changeType: 'up', sparkline: [-1.5, 0, 1.4, 3.2, 4.9, 6.0] },
          { label: 'Order Frequency', value: '3.6', suffix: '/mo', change: '+0.2 QoQ', changeType: 'up', sparkline: [2.4, 2.7, 3.0, 3.3, 3.5, 3.6] },
          { label: 'Ads Share of Revenue', value: '34', suffix: '%', change: '+3pp QoQ', changeType: 'up', sparkline: [16, 19, 24, 27, 31, 34] },
        ] },
      'Q4-2026': { temperature: 62, consensus: 'CONSENSUS BULL', headline: 'Festive demand and q-commerce synergy deliver a record contribution-margin year.',
        keyMetrics: [
          { label: 'Gross Order Value', value: '45,500', suffix: '₹ Cr', change: '+27% YoY', changeType: 'up', sparkline: [24, 30, 35, 39, 42, 45.5] },
          { label: 'Zomato Contribution Margin', value: '6.6', suffix: '%', change: '+0.6pp QoQ', changeType: 'up', sparkline: [-1.2, 0.3, 1.8, 3.6, 5.4, 6.6] },
          { label: 'Order Frequency', value: '3.8', suffix: '/mo', change: '+0.2 QoQ', changeType: 'up', sparkline: [2.5, 2.9, 3.2, 3.5, 3.7, 3.8] },
          { label: 'Ads Share of Revenue', value: '36', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [17, 20, 26, 30, 33, 36] },
        ] },
    },
    subSectors: [
      { name: 'Aggregators', share: 52, growth: '+22% YoY', cagr: '16%', players: ['Zomato', 'Swiggy'] },
      { name: 'Quick Service (QSR)', share: 24, growth: '+14% YoY', cagr: '12%', players: ["Domino's", 'Burger King', 'KFC'] },
      { name: 'Cloud Kitchens', share: 14, growth: '+28% YoY', cagr: '20%', players: ['Rebel Foods', 'Curefoods'] },
      { name: 'Dine-in & Discovery', share: 10, growth: '+18% YoY', cagr: '14%', players: ['Zomato', 'Swiggy Dineout', 'EazyDiner'] },
    ],
    competitive: [
      { player: 'Zomato', rank: 1, metric: 'Order Volume', value: '~55%', trend: 'up', note: 'Leader; strong in q-commerce via Blinkit' },
      { player: 'Swiggy', rank: 2, metric: 'Order Volume', value: '~42%', trend: 'flat', note: 'Improving economics, Instamart scaling' },
      { player: 'EatSure / Rebel Foods', rank: 3, metric: 'Cloud Kitchen', value: '~30%', trend: 'up', note: 'Own-brand + multi-brand model' },
      { player: "Domino's India", rank: 4, metric: 'QSR Delivery', value: '~28%', trend: 'flat', note: 'Strong delivery network' },
    ],
    trends: [
      { title: 'Contribution Margin Inflection', impact: 'High', direction: 'up', description: 'Both majors now contribution-positive on the back of take-rate discipline and ads.' },
      { title: 'Ads & Subscriptions', impact: 'High', direction: 'up', description: 'Advertisement income is becoming a material share of platform revenue.' },
      { title: 'Premium & Dine-in Push', impact: 'Medium', direction: 'up', description: 'Higher-ticket segments and dining rewards drive ASP growth.' },
      { title: 'Blurred Lines with q-commerce', impact: 'High', direction: 'up', description: 'Aggregators extend delivery into instant commerce, expanding TAM.' },
    ],
    regulatory: [
      { title: 'Delivery Partner Conditions', date: 'Under review', status: 'Pending', description: 'Wage and working-condition guidelines for gig delivery partners.' },
      { title: 'FSSAI Hygiene Ratings', date: 'Ongoing', status: 'Implemented', description: 'Mandatory hygiene rating display for listed restaurants.' },
      { title: 'Platform-Pricing Transparency', date: 'Q4 2026', status: 'Planned', description: 'Disclosure norms on delivery and platform fees.' },
    ],
    swot: {
      strengths: ['Dominant category leaders', 'Diversified revenue (ads, q-commerce)', 'Delivery network density'],
      weaknesses: ['Restaurant margin squeeze', 'Gig workforce cost', 'Promo dependence in India'],
      opportunities: ['Hyper-local q-commerce', 'Own-brand / private label', 'International expansion'],
      threats: ['Regulatory wage rules', 'Aggressive discounting', 'New entrants in instant delivery'],
    },
    outlook: {
      marketSize2027: '₹45,000 Cr', cagr: '16%',
      projection: [{ year: '2024', value: 22 }, { year: '2025', value: 29 }, { year: '2026', value: 35 }, { year: '2027', value: 45 }],
      drivers: ['Margin expansion', 'Ads growth', 'Instant commerce'],
      risks: ['Gig regulation', 'Food inflation', 'Competition'],
    },
    catalysts: [
      { title: 'Swiggy profitability milestone', timing: 'FY27', type: 'Catalyst' },
      { title: 'Gig-worker policy', timing: 'Q3 2026', type: 'Risk' },
      { title: 'Zomato-Hyperpure scaling', timing: 'Ongoing', type: 'Watch' },
    ],
    proMetrics: [
      { label: 'Commission Rate (avg)', value: '18-22%', note: 'varies by tier', trend: 'flat' },
      { label: 'Restaurant Net Margin', value: '3.5%', note: 'after platform fees', trend: 'flat' },
      { label: 'Delivery Partner Earning/hr', value: '₹78', note: 'incl. incentives', trend: 'down' },
      { label: 'Blinkit Contribution Margin', value: '+3.1%', note: 'of GOV', trend: 'up' },
      { label: 'Take Rate (Zomato food)', value: '26%', note: 'gross', trend: 'up' },
      { label: 'Instamart Contribution Margin', value: '-1.2%', note: 'improving', trend: 'up' },
    ],
  },
  {
    slug: 'saas', name: 'Enterprise SaaS', shortName: 'SaaS', icon: '☁️',
    tagline: 'Cloud, AI & enterprise software', coverGradient: ['#2563eb', '#1e3a8a'],
    thesis: 'Indian SaaS is transitioning from services-led to AI-native, horizontal products. The growth levers are generative-AI features, Net Revenue Retention (NRR) expansion, and enterprise cloud adoption. The valuation multiple has normalised, rewarding capital-efficient growth and profitability.',
    quarters: {
      'Q1-2026': { temperature: 70, consensus: 'CONSENSUS BULL', headline: 'Enterprise cloud adoption accelerating — a $25B Indian SaaS market by 2027, led by AI-native products.',
        keyMetrics: [
          { label: 'Indian SaaS Revenue', value: '13', suffix: '$B', change: '+35% YoY', changeType: 'up', sparkline: [6.2, 7.5, 8.8, 10.4, 11.8, 13] },
          { label: 'SaaS Unicorns', value: '12', suffix: 'as of 2025', change: '+3 YoY', changeType: 'up', sparkline: [6, 7, 9, 10, 11, 12] },
          { label: 'Enterprise Cloud Adoption', value: '68', suffix: '%', change: '+18pp YoY', changeType: 'up', sparkline: [32, 40, 48, 56, 63, 68] },
          { label: 'Median Net Revenue Retention', value: '112', suffix: '%', change: '+3pp YoY', changeType: 'up', sparkline: [103, 105, 107, 109, 111, 112] },
        ] },
      'Q2-2026': { temperature: 72, consensus: 'CONSENSUS BULL', headline: 'AI-feature monetisation lifts ASPs and NRR as capital efficiency and Rule-of-40 become the norm.',
        keyMetrics: [
          { label: 'Indian SaaS Revenue', value: '15', suffix: '$B', change: '+38% YoY', changeType: 'up', sparkline: [6.6, 8.2, 10.0, 12.0, 13.5, 15] },
          { label: 'SaaS Unicorns', value: '14', suffix: 'as of 2026', change: '+2 YTD', changeType: 'up', sparkline: [6.5, 8, 10, 11, 12, 14] },
          { label: 'Enterprise Cloud Adoption', value: '72', suffix: '%', change: '+4pp QoQ', changeType: 'up', sparkline: [35, 44, 52, 60, 66, 72] },
          { label: 'Median Net Revenue Retention', value: '114', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [104, 106, 109, 111, 112, 114] },
        ] },
      'Q3-2026': { temperature: 73, consensus: 'CONSENSUS BULL', headline: 'Vertical AI SaaS and India enterprise cloud drive a record deal pipeline.',
        keyMetrics: [
          { label: 'Indian SaaS Revenue', value: '17.2', suffix: '$B', change: '+40% YoY', changeType: 'up', sparkline: [7, 9, 11.2, 13.5, 15.2, 17.2] },
          { label: 'SaaS Unicorns', value: '16', suffix: 'as of 2026', change: '+2 QoQ', changeType: 'up', sparkline: [7, 9, 11, 12, 14, 16] },
          { label: 'AI-Feature Uptake', value: '64', suffix: '%', change: 'of product lines', changeType: 'up', sparkline: [18, 30, 42, 50, 58, 64] },
          { label: 'Median Net Revenue Retention', value: '115', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [104, 107, 110, 112, 113, 115] },
        ] },
      'Q4-2026': { temperature: 74, consensus: 'CONSENSUS BULL', headline: 'A resilient year as AI-native SaaS firms expand globally with strong margins.',
        keyMetrics: [
          { label: 'Indian SaaS Revenue', value: '19.5', suffix: '$B', change: '+42% YoY', changeType: 'up', sparkline: [7.5, 9.8, 12.5, 15, 17, 19.5] },
          { label: 'SaaS Unicorns', value: '18', suffix: 'as of 2026', change: '+2 QoQ', changeType: 'up', sparkline: [7.5, 9.5, 12, 13.5, 16, 18] },
          { label: 'AI-Feature Uptake', value: '70', suffix: '%', change: 'of product lines', changeType: 'up', sparkline: [20, 33, 46, 55, 63, 70] },
          { label: 'Median Net Revenue Retention', value: '116', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [105, 108, 111, 113, 114, 116] },
        ] },
    },
    subSectors: [
      { name: 'Horizontal SaaS', share: 40, growth: '+30% YoY', cagr: '24%', players: ['Zoho', 'Freshworks', 'Chargebee'] },
      { name: 'Vertical SaaS', share: 30, growth: '+38% YoY', cagr: '28%', players: ['Whatfix', 'Postman', 'BrowserStack'] },
      { name: 'AI / Data SaaS', share: 18, growth: '+55% YoY', cagr: '40%', players: ['Fractal', 'Turing', 'Flock'] },
      { name: 'Developer Tools', share: 12, growth: '+42% YoY', cagr: '32%', players: ['Postman', 'BrowserStack', 'Hasura'] },
    ],
    competitive: [
      { player: 'Zoho', rank: 1, metric: 'ARR Scale', value: '>$1B', trend: 'up', note: 'Largest bootstrapped SaaS player' },
      { player: 'Freshworks', rank: 2, metric: 'ARR Scale', value: '~$600M', trend: 'up', note: 'Public, profitability improving' },
      { player: 'Postman', rank: 3, metric: 'Developer Adoption', value: '>35M', trend: 'up', note: 'API-first category leader' },
      { player: 'Chargebee', rank: 4, metric: 'Revenue Growth', value: 'High', trend: 'flat', note: 'Subscription-billing scale-up' },
    ],
    trends: [
      { title: 'AI-Feature Monetisation', impact: 'High', direction: 'up', description: 'Gen-AI add-ons lifting ASPs and NRR across product suites.' },
      { title: 'Efficiency Over Growth', impact: 'High', direction: 'flat', description: 'Founders prioritise Rule-of-40 and cash flow over raw ARR growth.' },
      { title: 'Vertical & GTM Specialisation', impact: 'Medium', direction: 'up', description: 'Vertical SaaS and industry-specific workflows winning enterprise deals.' },
      { title: 'Global-GTM via Product-Led Growth', impact: 'Medium', direction: 'up', description: 'PLG and self-serve lowering CAC for global expansion.' },
    ],
    regulatory: [
      { title: 'Data Localisation (DPDP)', date: 'Mar 2026', status: 'Pending', description: 'Data-residency and fiduciary obligations for SaaS handling personal data.' },
      { title: 'AI Governance Framework', date: 'Q4 2026', status: 'Planned', description: 'Proposed principles for responsible and accountable AI systems.' },
      { title: 'Cloud Security (CERT-In)', date: 'Ongoing', status: 'Implemented', description: 'Incident reporting and security norms for cloud providers.' },
    ],
    swot: {
      strengths: ['Large engineering talent pool', 'Cost advantage in GTM', 'Strong product-led culture'],
      weaknesses: ['Low enterprise wallet share', 'Dollar exposure risk', 'Thin global brand awareness'],
      opportunities: ['AI-native products', 'Vertical SaaS', 'India enterprise cloud'],
      threats: ['Valuation normalisation', 'US macro slowdown', 'Data-localisation friction'],
    },
    outlook: {
      marketSize2027: '$25B', cagr: '28%',
      projection: [{ year: '2024', value: 10 }, { year: '2025', value: 13 }, { year: '2026', value: 18 }, { year: '2027', value: 25 }],
      drivers: ['AI monetisation', 'Enterprise cloud', 'Global GTM'],
      risks: ['Funding gap', 'Global slowdown', 'Talent cost'],
    },
    catalysts: [
      { title: 'AI-feature ARPU uplift', timing: 'FY27', type: 'Catalyst' },
      { title: 'SaaS IPO window reopening', timing: 'H2 2026', type: 'Watch' },
      { title: 'US enterprise IT budget cuts', timing: 'Ongoing', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Median NRR', value: '114%', note: 'top-50 Indian SaaS', trend: 'up' },
      { label: 'Median Gross Margin', value: '78%', note: 'product companies', trend: 'up' },
      { label: 'Median CAC Payback', value: '18 months', note: 'top-quartile', trend: 'down' },
      { label: 'ARR Multiple (private)', value: '9.2x', note: 'median 2026', trend: 'flat' },
      { label: 'Rule-of-40 Compliance', value: '54%', note: 'of tracked firms', trend: 'up' },
      { label: 'AI-Feature ARPU Uplift', value: '+16%', note: 'net of plan changes', trend: 'up' },
    ],
  },
  {
    slug: 'd2c', name: 'D2C Brands', shortName: 'D2C', icon: '🛍️',
    tagline: 'Direct-to-consumer & new-age brands', coverGradient: ['#db2777', '#831843'],
    thesis: 'The D2C story has shifted from top-line storytelling to contribution discipline. Brands that pair strong repeat purchase with omnichannel and private-label economics are consolidating share, while CAC-heavy, low-retention brands are being rationalised.',
    quarters: {
      'Q1-2026': { temperature: 62, consensus: 'CONSENSUS BULL', headline: 'D2C capturing 15% of organized retail — profitability is the new battleground.',
        keyMetrics: [
          { label: 'D2C Market Size', value: '55,000', suffix: '₹ Cr', change: '+40% YoY', changeType: 'up', sparkline: [22, 30, 38, 44, 50, 55] },
          { label: 'D2C Share of Organized Retail', value: '15', suffix: '%', change: '+4pp YoY', changeType: 'up', sparkline: [7, 9, 11, 13, 14, 15] },
          { label: 'EBITDA+ D2C Brands', value: '38', suffix: '%', change: '+12pp YoY', changeType: 'up', sparkline: [18, 22, 26, 30, 34, 38] },
          { label: 'Average Repeat Purchase Rate', value: '34', suffix: '%', change: '+6pp YoY', changeType: 'up', sparkline: [22, 25, 28, 30, 32, 34] },
        ] },
      'Q2-2026': { temperature: 64, consensus: 'CONSENSUS BULL', headline: 'Omnichannel and subscription models lift repeat rates and EBITDA margins for scale players.',
        keyMetrics: [
          { label: 'D2C Market Size', value: '62,000', suffix: '₹ Cr', change: '+43% YoY', changeType: 'up', sparkline: [25, 34, 43, 50, 56, 62] },
          { label: 'D2C Share of Organized Retail', value: '16', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [7.5, 10, 12, 14, 15, 16] },
          { label: 'EBITDA+ D2C Brands', value: '42', suffix: '%', change: '+4pp QoQ', changeType: 'up', sparkline: [20, 25, 30, 34, 38, 42] },
          { label: 'Average Repeat Purchase Rate', value: '36', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [23, 27, 30, 32, 34, 36] },
        ] },
      'Q3-2026': { temperature: 65, consensus: 'CONSENSUS BULL', headline: 'Brands double down on private labels and international expansion as CAC normalises.',
        keyMetrics: [
          { label: 'D2C Market Size', value: '70,000', suffix: '₹ Cr', change: '+45% YoY', changeType: 'up', sparkline: [28, 38, 48, 56, 63, 70] },
          { label: 'D2C Share of Organized Retail', value: '17', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [8, 11, 13.5, 15.5, 16.5, 17] },
          { label: 'EBITDA+ D2C Brands', value: '45', suffix: '%', change: '+3pp QoQ', changeType: 'up', sparkline: [22, 27, 33, 37, 41, 45] },
          { label: 'Average Repeat Purchase Rate', value: '38', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [24, 28, 32, 34, 36, 38] },
        ] },
      'Q4-2026': { temperature: 66, consensus: 'CONSENSUS BULL', headline: 'Festive season and offline expansion cement D2C profitability across the portfolio.',
        keyMetrics: [
          { label: 'D2C Market Size', value: '78,000', suffix: '₹ Cr', change: '+46% YoY', changeType: 'up', sparkline: [31, 42, 53, 62, 70, 78] },
          { label: 'D2C Share of Organized Retail', value: '18', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [8.5, 12, 15, 17, 17.5, 18] },
          { label: 'EBITDA+ D2C Brands', value: '48', suffix: '%', change: '+3pp QoQ', changeType: 'up', sparkline: [24, 29, 36, 40, 44, 48] },
          { label: 'Average Repeat Purchase Rate', value: '40', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [25, 30, 34, 36, 38, 40] },
        ] },
    },
    subSectors: [
      { name: 'Beauty & Personal Care', share: 34, growth: '+42% YoY', cagr: '30%', players: ['Mamaearth', 'Plum', 'Minimalist'] },
      { name: 'Fashion & Accessories', share: 24, growth: '+28% YoY', cagr: '22%', players: ['Bewakoof', 'The Souled Store'] },
      { name: 'Food & Beverage', share: 20, growth: '+38% YoY', cagr: '26%', players: ['Whole Foods', 'Bakingo'] },
      { name: 'Home & D\u00e9cor', share: 12, growth: '+24% YoY', cagr: '18%', players: ['The Sleep Company', 'Wakefit'] },
      { name: 'Personal Care (oral/hair)', share: 10, growth: '+35% YoY', cagr: '24%', players: ['Perfora', 'Sensai'] },
    ],
    competitive: [
      { player: 'Mamaearth (Honasa)', rank: 1, metric: 'Revenue Scale', value: '>₹2,000 Cr', trend: 'flat', note: 'Beauty leader, investing in profitability' },
      { player: 'Plum', rank: 2, metric: 'Growth', value: 'High', trend: 'up', note: 'Clean-beauty, strong omnichannel' },
      { player: 'The Sleep Company', rank: 3, metric: 'EBITDA', value: 'Positive', trend: 'up', note: 'Innovative product + high margins' },
      { player: 'Wakefit', rank: 4, metric: 'Market Share (sleep)', value: 'Leader', trend: 'up', note: 'Digitally-led, expanding offline' },
    ],
    trends: [
      { title: 'Omnichannel Mandate', impact: 'High', direction: 'up', description: 'Winning brands blend D2C, marketplaces and offline retail for full funnel.' },
      { title: 'CAC Discipline & LTV Focus', impact: 'High', direction: 'flat', description: 'Brands cut performance-marketing spend and double down on retention.' },
      { title: 'Private-label & GTM Innovation', impact: 'Medium', direction: 'up', description: 'Own-manufacturing and subscription models lifting unit economics.' },
      { title: 'AI Personalisation', impact: 'Medium', direction: 'up', description: 'Gen-AI-driven product discovery and repeat-purchase engines.' },
    ],
    regulatory: [
      { title: 'Consumer Protection (D2C)', date: 'Ongoing', status: 'Implemented', description: 'Misleading-ad and influencer-disclosure enforcement.' },
      { title: 'E-commerce Marketplace Rules', date: 'Q3 2026', status: 'Pending', description: 'Related-party and inventory norms for platforms.' },
      { title: 'Green Claims Guidelines', date: 'Q4 2026', status: 'Planned', description: 'Substantiation for eco-friendly product claims.' },
    ],
    swot: {
      strengths: ['Digital-first brand building', 'Deep consumer data', 'Agile product iteration'],
      weaknesses: ['High customer acquisition cost', 'Offline scaling complexity', 'Platform dependence'],
      opportunities: ['Offline & omnichannel', 'Subscription models', 'International expansion'],
      threats: ['Platform commission changes', 'Incumbent counterattack', 'Ad-cost inflation'],
    },
    outlook: {
      marketSize2027: '₹75,000 Cr', cagr: '26%',
      projection: [{ year: '2024', value: 30 }, { year: '2025', value: 44 }, { year: '2026', value: 55 }, { year: '2027', value: 75 }],
      drivers: ['Omnichannel', 'Repeat purchase', 'Premiumisation'],
      risks: ['CAC inflation', 'Competition', 'Macro slowdown'],
    },
    catalysts: [
      { title: 'D2C IPO pipeline', timing: 'H2 2026', type: 'Watch' },
      { title: 'Offline retail expansion by top brands', timing: 'FY27', type: 'Catalyst' },
      { title: 'Marketplace commission review', timing: 'Q3 2026', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Median Contribution Margin', value: '38%', note: 'top-50 D2C brands', trend: 'up' },
      { label: 'Blended CAC', value: '₹680', note: 'all channels', trend: 'down' },
      { label: 'Repeat Purchase Rate (30d)', value: '36%', note: 'beauty & F&B', trend: 'up' },
      { label: 'Offline Share of Revenue', value: '24%', note: 'top-20 brands', trend: 'up' },
      { label: 'Return on Ad Spend (ROAS)', value: '2.8x', note: 'blended digital', trend: 'flat' },
      { label: 'Private-Label Margin Premium', value: '+9pp', note: 'vs third-party', trend: 'up' },
    ],
  },
  {
    slug: 'healthcare', name: 'HealthTech', shortName: 'Health', icon: '🏥',
    tagline: 'Telemedicine, pharmacy, diagnostics & hospital tech', coverGradient: ['#0ea5e9', '#155e75'],
    thesis: 'HealthTech is maturing across pharma, diagnostics, telemedicine and hospital SaaS. The adoption curve has flattened from pandemic highs but deepened, with insurance-linked care, chronic management and B2B2C models driving durable, high-quality growth.',
    quarters: {
      'Q1-2026': { temperature: 60, consensus: 'CONSENSUS BULL', headline: 'Digital health adoption surges — a ₹35,000 Cr addressable market by 2026.',
        keyMetrics: [
          { label: 'Digital Health Users', value: '280', suffix: 'M', change: '+65% YoY', changeType: 'up', sparkline: [120, 160, 200, 235, 260, 280] },
          { label: 'Telemedicine Consultations', value: '450', suffix: 'M', change: '+110% YoY', changeType: 'up', sparkline: [140, 210, 290, 360, 410, 450] },
          { label: 'HealthTech Funding (FY25)', value: '1.8', suffix: '$B', change: '+22% YoY', changeType: 'up', sparkline: [1.1, 1.3, 1.4, 1.6, 1.7, 1.8] },
          { label: 'Online Pharmacy Penetration', value: '11', suffix: '%', change: '+3pp YoY', changeType: 'up', sparkline: [4, 5, 7, 8, 10, 11] },
        ] },
      'Q2-2026': { temperature: 61, consensus: 'CONSENSUS BULL', headline: 'Insurance-linked care and chronic-management subscriptions deepen engagement and margins.',
        keyMetrics: [
          { label: 'Digital Health Users', value: '310', suffix: 'M', change: '+70% YoY', changeType: 'up', sparkline: [130, 175, 220, 258, 284, 310] },
          { label: 'Telemedicine Consultations', value: '520', suffix: 'M', change: '+115% YoY', changeType: 'up', sparkline: [155, 235, 320, 400, 460, 520] },
          { label: 'HealthTech Funding (YTD)', value: '1.2', suffix: '$B', change: 'strong pipeline', changeType: 'up', sparkline: [1.1, 1.3, 1.4, 1.6, 1.7, 1.2] },
          { label: 'Online Pharmacy Penetration', value: '12', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [4.2, 5.5, 7.5, 9, 10.5, 12] },
        ] },
      'Q3-2026': { temperature: 62, consensus: 'CONSENSUS BULL', headline: 'Diagnostics integration and B2B health SaaS create sticky recurring revenue.',
        keyMetrics: [
          { label: 'Digital Health Users', value: '340', suffix: 'M', change: '+72% YoY', changeType: 'up', sparkline: [140, 190, 240, 280, 310, 340] },
          { label: 'Telemedicine Consultations', value: '590', suffix: 'M', change: '+118% YoY', changeType: 'up', sparkline: [170, 260, 350, 440, 500, 590] },
          { label: 'At-home Diagnostics Orders', value: '22', suffix: 'M/yr', change: '+45% YoY', changeType: 'up', sparkline: [6, 10, 14, 17, 19, 22] },
          { label: 'Online Pharmacy Penetration', value: '13', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [4.5, 6, 8, 10, 11.5, 13] },
        ] },
      'Q4-2026': { temperature: 63, consensus: 'CONSENSUS BULL', headline: 'NDHM digital-health ID and insurance integration mark a milestone year for HealthTech.',
        keyMetrics: [
          { label: 'Digital Health Users', value: '375', suffix: 'M', change: '+75% YoY', changeType: 'up', sparkline: [150, 205, 260, 305, 340, 375] },
          { label: 'Telemedicine Consultations', value: '660', suffix: 'M', change: '+120% YoY', changeType: 'up', sparkline: [185, 280, 380, 475, 545, 660] },
          { label: 'At-home Diagnostics Orders', value: '27', suffix: 'M/yr', change: '+48% YoY', changeType: 'up', sparkline: [7, 11, 16, 20, 23, 27] },
          { label: 'Online Pharmacy Penetration', value: '14', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [5, 6.5, 9, 11, 12.5, 14] },
        ] },
    },
    subSectors: [
      { name: 'Online Pharmacy', share: 34, growth: '+38% YoY', cagr: '28%', players: ['PharmEasy', 'Tata 1mg', 'Apollo 24/7'] },
      { name: 'Diagnostics', share: 26, growth: '+30% YoY', cagr: '22%', players: ['Lal PathLabs', 'Dr Lal', 'Redcliffe'] },
      { name: 'Telemedicine', share: 18, growth: '+110% YoY', cagr: '42%', players: ['Apollo 24/7', 'Practo', 'MFine'] },
      { name: 'Hospital & Health SaaS', share: 12, growth: '+35% YoY', cagr: '26%', players: ['Practo', 'HealthPlix', 'Zeno Health'] },
      { name: 'Insurtech Health', share: 10, growth: '+48% YoY', cagr: '32%', players: ['Plum', 'Digit Health', 'CareHealth'] },
    ],
    competitive: [
      { player: 'Tata 1mg', rank: 1, metric: 'Pharmacy Scale', value: 'Leader', trend: 'up', note: 'Trusted brand, expanding diagnostics' },
      { player: 'PharmEasy', rank: 2, metric: 'Revenue Scale', value: 'High', trend: 'flat', note: 'Restructuring toward profitability' },
      { player: 'Apollo 24/7', rank: 3, metric: 'Omnichannel', value: 'Strong', trend: 'up', note: 'Leverages Apollo hospital network' },
      { player: 'Practo', rank: 4, metric: 'SaaS + Telemedicine', value: 'High', trend: 'up', note: 'B2B SaaS for clinics scaling' },
    ],
    trends: [
      { title: 'Insurance-Linked Care', impact: 'High', direction: 'up', description: 'Cashless, integrated digital health with insurers is the key adoption driver.' },
      { title: 'Chronic & Preventive Care', impact: 'High', direction: 'up', description: 'Subscription chronic-management programs lift LTV and margins.' },
      { title: 'Diagnostics Integration', impact: 'Medium', direction: 'up', description: 'Platforms adding at-home diagnostics to own the full care pathway.' },
      { title: 'B2B2C Health SaaS', impact: 'Medium', direction: 'up', description: 'Clinic and hospital SaaS products creating sticky recurring revenue.' },
    ],
    regulatory: [
      { title: 'Telemedicine Guidelines', date: 'Ongoing', status: 'Implemented', description: 'Updated eSanjeevani and teleconsultation practice norms.' },
      { title: 'Digital Health Authority (NDHM)', date: 'FY27', status: 'Pending', description: 'Unified digital health ID and records interoperability.' },
      { title: 'Online Pharmacy Rules', date: 'Q3 2026', status: 'Planned', description: 'Draft e-pharmacy regulations under the Drugs Act.' },
    ],
    swot: {
      strengths: ['Deep pharma supply chains', 'Telemedicine acceptance', 'Insurance integration'],
      weaknesses: ['Low margins in pharmacy', 'Regulatory uncertainty', 'Consumer trust gaps'],
      opportunities: ['Chronic-care subscription', 'Diagnostics-at-home', 'B2B health SaaS'],
      threats: ['E-pharmacy regulation', 'Drug pricing control', 'Data-privacy rules'],
    },
    outlook: {
      marketSize2027: '₹45,000 Cr', cagr: '30%',
      projection: [{ year: '2024', value: 20 }, { year: '2025', value: 29 }, { year: '2026', value: 35 }, { year: '2027', value: 45 }],
      drivers: ['Insurance linkage', 'Chronic care', 'Diagnostics'],
      risks: ['Regulation', 'Low margins', 'Competition'],
    },
    catalysts: [
      { title: 'NDHM digital-health rollout', timing: 'FY27', type: 'Catalyst' },
      { title: 'E-pharmacy regulation', timing: 'Q3 2026', type: 'Risk' },
      { title: 'Chronic-care subscription scaling', timing: 'Ongoing', type: 'Watch' },
    ],
    proMetrics: [
      { label: 'Online Pharmacy Gross Margin', value: '18%', note: 'blended', trend: 'up' },
      { label: 'Chronic-Care Subscription Retention', value: '74%', note: '12-month', trend: 'up' },
      { label: 'Diagnostics Take Rate', value: '22%', note: 'platform', trend: 'up' },
      { label: 'Hospital SaaS ARPA', value: '₹2.4L', note: 'per facility/yr', trend: 'up' },
      { label: 'Telemedicine Cost per Consult', value: '₹41', note: 'platform', trend: 'down' },
      { label: 'Insurtech Health GMV', value: '₹8,200 Cr', note: 'annualised', trend: 'up' },
    ],
  },
  {
    slug: 'edtech', name: 'EdTech', shortName: 'EdTech', icon: '📚',
    tagline: 'K-12, higher-ed, test prep & enterprise L&D', coverGradient: ['#7c3aed', '#4c1d95'],
    thesis: 'EdTech has reset from hyper-growth to sustainable, hybrid delivery. The shakeout cleared out unprofitable scale; the survivors are high-retention, hybrid and profitable. Enterprise L&D and AI-tutoring represent the most durable growth vectors.',
    quarters: {
      'Q1-2026': { temperature: 52, consensus: 'NEUTRAL', headline: 'Online learning stabilizing post-BYJU\'s — hybrid models and profitability are the new winners.',
        keyMetrics: [
          { label: 'Online Learning Market', value: '50,000', suffix: '₹ Cr', change: '+18% YoY', changeType: 'up', sparkline: [30, 36, 42, 46, 48, 50] },
          { label: 'Active EdTech Users', value: '90', suffix: 'M', change: '+8% YoY', changeType: 'flat', sparkline: [70, 78, 85, 88, 89, 90] },
          { label: 'Avg. Completion Rate', value: '22', suffix: '%', change: '-3pp YoY', changeType: 'down', sparkline: [26, 26, 25, 24, 23, 22] },
          { label: 'Enterprise L&D Spend', value: '12,500', suffix: '₹ Cr', change: '+30% YoY', changeType: 'up', sparkline: [5, 7, 9, 10, 11, 12.5] },
        ] },
      'Q2-2026': { temperature: 54, consensus: 'CONSENSUS BULL', headline: 'Enterprise L&D and AI-tutoring lift retention as the sector rebuilds on profitable growth.',
        keyMetrics: [
          { label: 'Online Learning Market', value: '53,000', suffix: '₹ Cr', change: '+20% YoY', changeType: 'up', sparkline: [32, 38, 45, 49, 51, 53] },
          { label: 'Active EdTech Users', value: '92', suffix: 'M', change: '+9% YoY', changeType: 'up', sparkline: [72, 80, 86, 89, 90, 92] },
          { label: 'Avg. Completion Rate', value: '23', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [26, 26, 25, 24, 23, 23] },
          { label: 'Enterprise L&D Spend', value: '14,000', suffix: '₹ Cr', change: '+33% YoY', changeType: 'up', sparkline: [5.5, 7.5, 10, 11.5, 12.5, 14] },
        ] },
      'Q3-2026': { temperature: 56, consensus: 'CONSENSUS BULL', headline: 'AI tutoring scales and enterprise L&D contract wins drive a durable upswing.',
        keyMetrics: [
          { label: 'Online Learning Market', value: '56,500', suffix: '₹ Cr', change: '+21% YoY', changeType: 'up', sparkline: [34, 41, 48, 52, 54, 56.5] },
          { label: 'AI-Tutor Sessions', value: '310', suffix: 'M', change: 'new metric', changeType: 'up', sparkline: [30, 80, 150, 210, 260, 310] },
          { label: 'Avg. Completion Rate', value: '25', suffix: '%', change: '+2pp QoQ', changeType: 'up', sparkline: [26, 26, 25, 24, 24, 25] },
          { label: 'Enterprise L&D Spend', value: '15,500', suffix: '₹ Cr', change: '+35% YoY', changeType: 'up', sparkline: [6, 8.5, 11, 13, 14, 15.5] },
        ] },
      'Q4-2026': { temperature: 57, consensus: 'CONSENSUS BULL', headline: 'A stabilising year: hybrid delivery, AI personalisation and enterprise demand reset EdTech on profitable footing.',
        keyMetrics: [
          { label: 'Online Learning Market', value: '60,000', suffix: '₹ Cr', change: '+22% YoY', changeType: 'up', sparkline: [36, 44, 51, 55, 58, 60] },
          { label: 'AI-Tutor Sessions', value: '420', suffix: 'M', change: '+35% QoQ', changeType: 'up', sparkline: [35, 95, 180, 250, 320, 420] },
          { label: 'Avg. Completion Rate', value: '26', suffix: '%', change: '+1pp QoQ', changeType: 'up', sparkline: [26, 26, 25, 24, 25, 26] },
          { label: 'Enterprise L&D Spend', value: '17,000', suffix: '₹ Cr', change: '+36% YoY', changeType: 'up', sparkline: [6.5, 9.5, 12, 14.5, 16, 17] },
        ] },
    },
    subSectors: [
      { name: 'Test Prep', share: 32, growth: '+15% YoY', cagr: '12%', players: ["BYJU's", 'Physics Wallah', 'Unacademy'] },
      { name: 'K-12', share: 26, growth: '+12% YoY', cagr: '10%', players: ['Vedantu', "BYJU's", 'Toppr'] },
      { name: 'Higher Ed & Upskilling', share: 24, growth: '+28% YoY', cagr: '20%', players: ['upGrad', 'Simplilearn', 'Great Learning'] },
      { name: 'Enterprise L&D', share: 18, growth: '+30% YoY', cagr: '22%', players: ['Disprz', 'NIIT', 'Edureka'] },
    ],
    competitive: [
      { player: 'Physics Wallah', rank: 1, metric: 'Affordable Scale', value: 'High', trend: 'up', note: 'Profitable, huge tier-2/3 reach' },
      { player: 'Unacademy', rank: 2, metric: 'Test-Prep Reach', value: 'High', trend: 'flat', note: 'Restructuring toward profitability' },
      { player: 'upGrad', rank: 3, metric: 'Higher-Ed', value: 'Leader', trend: 'up', note: 'Degree & certificate programs' },
      { player: 'Disprz', rank: 4, metric: 'Enterprise L&D', value: 'High', trend: 'up', note: 'AI-driven workforce learning' },
    ],
    trends: [
      { title: 'Hybrid Delivery Wins', impact: 'High', direction: 'up', description: 'Blended online-offline models show the highest completion and retention.' },
      { title: 'Affordability Reshapes Pricing', impact: 'High', direction: 'flat', description: 'Affordable models (e.g., Physics Wallah) outgrow premium ones.' },
      { title: 'AI-Tutoring & Personalisation', impact: 'Medium', direction: 'up', description: 'Gen-AI tutors lower cost-to-serve and lift outcomes.' },
      { title: 'Enterprise L&D Uplift', impact: 'Medium', direction: 'up', description: 'Corporate upskilling budgets shift online — a durable B2B revenue stream.' },
    ],
    regulatory: [
      { title: 'Online Ed Code of Conduct', date: 'Ongoing', status: 'Implemented', description: 'Refund, grievance and ad-claim norms for edtech firms.' },
      { title: 'NEP 2020 Implementation', date: 'FY27', status: 'Pending', description: 'Digital-first and experiential-learning reforms in K-12.' },
      { title: 'UGC Online Degree Norms', date: 'Q3 2026', status: 'Planned', description: 'Revised recognition for online degree and certificate programs.' },
    ],
    swot: {
      strengths: ['Low-cost content delivery', 'Large learner base', 'AI tutor scalability'],
      weaknesses: ['Low completion rates', 'Sales-led CAC', 'Consumer trust erosion'],
      opportunities: ['Enterprise L&D', 'AI personalisation', 'Hybrid centres'],
      threats: ['Regulatory oversight', 'Free content alternatives', 'Funding drought'],
    },
    outlook: {
      marketSize2027: '₹60,000 Cr', cagr: '16%',
      projection: [{ year: '2024', value: 38 }, { year: '2025', value: 46 }, { year: '2026', value: 50 }, { year: '2027', value: 60 }],
      drivers: ['Enterprise L&D', 'AI tutoring', 'Hybrid model'],
      risks: ['Regulation', 'Retention', 'Competition'],
    },
    catalysts: [
      { title: 'AI tutor mainstream adoption', timing: 'FY27', type: 'Catalyst' },
      { title: 'Enterprise L&D contract wins', timing: 'Ongoing', type: 'Watch' },
      { title: 'UGC online-degree rules', timing: 'Q3 2026', type: 'Risk' },
    ],
    proMetrics: [
      { label: 'Cohort Retention (K-12)', value: '31%', note: 'year-2', trend: 'up' },
      { label: 'Higher-Ed Enrolment CAGR', value: '18%', note: 'blended', trend: 'up' },
      { label: 'Enterprise L&D Gross Margin', value: '61%', note: 'platform', trend: 'up' },
      { label: 'Sales-Led CAC', value: '₹4,800', note: 'test-prep', trend: 'down' },
      { label: 'AI-Tutor Cost per Session', value: '₹3.2', note: 'incremental', trend: 'down' },
      { label: 'Hybrid-Centre Contribution', value: '+11pp', note: 'vs online-only', trend: 'up' },
    ],
  },
];
